server:
  port: 8090

  
spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 3s
        pool:
          type: fixed
          max-connections: 200
          max-idle-time: 5000
          acquire-timeout: 10000
      routes: 
        - id: order-service
          predicates:
            - Path=/ms/order-service/**
          filters:
            - StripPrefix=2
          uri: lb://order-service
        - id: pay-service
          predicates:
            - Path=/ms/pay-service/**
          filters:
            - StripPrefix=1
          uri: http://localhost:9999/pay-service
          metadata:
            response-timeout: 5000
  application:
    name: xiaozou-gateway


#csp:
#  sentinel:
#    dashboard:
#      server: 127.0.0.1:8080
#    api:
#      port: 8719
#sentinel:
#  dashboard:
#    auth:
#      username: sentinel
#      password: sentinel