server:
  port: 8091
  
  servlet:
    context-path:
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  profiles:
    active: dev
#  application:
#    name: xiaozouTest
